---
- name: add key
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
  tags: install
- name: add repo
  apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  tags: install
- name: apt update
  apt:
      update_cache: yes
  tags: install
- name: install mongo
  apt:
      name: mongodb-org
      state: present
  tags: install

- name: enable service
  systemd:
      name: mongod
      enabled: yes
  tags: install

