---
- name: Install mongoDB
  hosts: db
  become: true
  vars:
   mongo_bind_ip: 0.0.0.0
  tasks:
    - name: add key
      apt_key:
         keyserver: hkp://keyserver.ubuntu.com:80
         id: EA312927
    - name: add repo 
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: apt update
      apt:
         update_cache: yes 
    - name: install mongo
      apt:
        name: mongodb-org
        state: present
    - name: enable service
      systemd:
        name: mongod
        enabled: yes
